version: '3.4'

services:
  backend.starter.engine.docker.linux:
    image: backend.starter-engine-docker-linux
    container_name: backend.starter
    build:
      context: .
      dockerfile: backend.starter.Engine.Docker.Linux/Dockerfile
    env_file:
      - .env
      - .env.secret
    ports:
      - "5000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "quadrant.local:192.168.85.5"
